version: '3.3'
services:
  bluetooth_dosimeter_ap:
    env_file:
      - ".env"
    extends:
      file: Bluetooth_Dosimeter_AP/docker-compose.yml
      service: _bluetooth_dosimeter_ap
  bluetooth_dosimeter_backend:
    env_file:
      - ".env"
    networks:
      - dockernet
    extends:
      file: Bluetooth_Dosimeter_Backend/docker-compose.yml
      service: _bluetooth_dosimeter_backend
  bluetooth_dosimeter_frontend:
    volumes:
      - "./map/:/bluetooth_dosimeter_frontend/build/assets/map/:r"
    env_file:
      - ".env"
    networks:
      - dockernet
    extends:
      file: Bluetooth_Dosimeter_Frontend/docker-compose.yml
      service: _bluetooth_dosimeter_frontend

networks:
    dockernet:
